services:
  financial-reports-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: financial-reports-mcp:latest
    container_name: financial-reports-mcp
    environment:
      - API_KEY=${API_KEY:-your_api_key_here}
      - API_BASE_URL=${API_BASE_URL:-https://api.financialreports.eu/}
      - USE_MOCK_API=${USE_MOCK_API:-True}
      - MCP_TRANSPORT=${MCP_TRANSPORT:-stdio}
    # When using stdio transport (Claude Desktop), use:
    # docker-compose run -i financial-reports-mcp
    
    # When using HTTP/SSE transport, uncomment these:
    # ports:
    #  - "${MCP_PORT:-8000}:${MCP_PORT:-8000}"
    # environment:
    #  - MCP_HOST=0.0.0.0
    #  - MCP_PORT=${MCP_PORT:-8000}

# Example for running with stdio (Claude Desktop):
# docker-compose run -i financial-reports-mcp
#
# Example for running with HTTP/SSE:
# MCP_TRANSPORT=sse docker-compose up -d
